name: Test and Heal

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Choose healing mode"
        required: true
        default: "error"
        type: choice
        options:
          - error
          - design
          - flowux
          - full

jobs:
  heal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run healing script
        run: |
          if [ "${{ github.event.inputs.mode }}" = "error" ]; then
            npm run error-fix
          elif [ "${{ github.event.inputs.mode }}" = "design" ]; then
            npm run design-fix
          elif [ "${{ github.event.inputs.mode }}" = "flowux" ]; then
            npm run flowux-fix
          elif [ "${{ github.event.inputs.mode }}" = "full" ]; then
            npm run error-fix
            npm run design-fix
            npm run flowux-fix
          fi

      - name: Run tests after healing
        run: npm test

      - name: Upload healed repo artifact
        if: ${{ github.event.inputs.mode == 'full' }}
        uses: actions/upload-artifact@v4
        with:
          name: healed-repo
          path: .
